-- MySQL Script generated by MySQL Workbench
-- Sun Nov 30 17:32:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `idClientes` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionarios` (
  `idFuncionarios` INT NOT NULL AUTO_INCREMENT,
  `nomeFuncionario` VARCHAR(45) NULL,
  PRIMARY KEY (`idFuncionarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `quantidadesProdutos` INT NOT NULL,
  PRIMARY KEY (`idProdutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Faturamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Faturamentos` (
  `idFaturamentos` INT NOT NULL AUTO_INCREMENT,
  `idComandas` INT NOT NULL,
  `totalDia` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`idFaturamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Premiacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Premiacoes` (
  `idPremiacoes` INT NOT NULL AUTO_INCREMENT,
  `idComandas` INT NOT NULL,
  PRIMARY KEY (`idPremiacoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comandas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comandas` (
  `idComandas` INT NOT NULL AUTO_INCREMENT,
  `idClientes` INT NOT NULL,
  `valorTotal` DECIMAL(8,2) NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`idComandas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItensComanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItensComanda` (
  `idItensComanda` INT NOT NULL AUTO_INCREMENT,
  `idComanda` INT NOT NULL,
  `idProdutos` INT NOT NULL,
  `idFuncionarios` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `precoHora` DECIMAL(8,2) NOT NULL,
  `total` DECIMAL(8,2) NOT NULL,
  `horaRetirada` TIME NOT NULL,
  `horaDevolvida` TIME NOT NULL,
  PRIMARY KEY (`idItensComanda`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
